### ISSUE TITLE
Contao 4.9 compatibility

### ISSUE THREAD

**Issue by fritzmg** [asconsulting/zyppy_popup#1]
This extension breaks the search indexing in Contao 4.9, since it replaces the `regular` page type, which then causes the JSON-LD information for the front end to be missing. See https://github.com/contao/contao/issues/1939

In order to fix it, you probably have to change 

https://github.com/asconsulting/zyppy_popup/blob/5dea18b2b0c6d37f957e2183a5400c9acfabd9c0/system/modules/zyppy_popup/library/Asc/Frontend/PagePopup.php#L223

to

```php
$this->createFooterScripts($objLayout, $objPage);
```

if you still need to register your own page type.

It would be better if you didn't replace the page type. Why exactly do you need to do that?

**Comment by asconsulting** [comment]
The module dynamically replaces the template and loads JS based on what elements/modules are on the page. There was no hook that could perform the same functionality, and had the information my module needed passed to it so I was forced to override the base page class.

I have updated my module to closer match the 4.9 PageRegular Class.
